# Generated by Django 5.0.4 on 2024-04-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активность'),
        ),
    ]
