# Generated by Django 5.0.4 on 2024-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_active_alter_file_date_alter_file_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='active',
            new_name='is_send',
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'confirmed'), ('REJECTED', 'rejected'), ('NONE', 'none')], default='NONE', max_length=100, verbose_name='статус'),
        ),
    ]
